/* automatically generated by rust-bindgen 0.72.1 */

pub const SOKOL_APP_INCLUDED: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 0;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 0;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_64_BIT_INO_T: &[u8; 9] = b"$INODE64\0";
pub const __DARWIN_SUF_1050: &[u8; 6] = b"$1050\0";
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub type wchar_t = ::std::os::raw::c_int;
pub type max_align_t = u128;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __darwin_pthread_handler_rec"]
        [::std::mem::size_of::<__darwin_pthread_handler_rec>() - 24usize];
    ["Alignment of __darwin_pthread_handler_rec"]
        [::std::mem::align_of::<__darwin_pthread_handler_rec>() - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__routine"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __routine) - 0usize];
    ["Offset of field: __darwin_pthread_handler_rec::__arg"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __arg) - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__next"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_attr_t"][::std::mem::size_of::<_opaque_pthread_attr_t>() - 64usize];
    ["Alignment of _opaque_pthread_attr_t"]
        [::std::mem::align_of::<_opaque_pthread_attr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_attr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_attr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_cond_t"][::std::mem::size_of::<_opaque_pthread_cond_t>() - 48usize];
    ["Alignment of _opaque_pthread_cond_t"]
        [::std::mem::align_of::<_opaque_pthread_cond_t>() - 8usize];
    ["Offset of field: _opaque_pthread_cond_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_cond_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_condattr_t"]
        [::std::mem::size_of::<_opaque_pthread_condattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_condattr_t"]
        [::std::mem::align_of::<_opaque_pthread_condattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_condattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_condattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutex_t"][::std::mem::size_of::<_opaque_pthread_mutex_t>() - 64usize];
    ["Alignment of _opaque_pthread_mutex_t"]
        [::std::mem::align_of::<_opaque_pthread_mutex_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutex_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutex_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutexattr_t"]
        [::std::mem::size_of::<_opaque_pthread_mutexattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_mutexattr_t"]
        [::std::mem::align_of::<_opaque_pthread_mutexattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_once_t"][::std::mem::size_of::<_opaque_pthread_once_t>() - 16usize];
    ["Alignment of _opaque_pthread_once_t"]
        [::std::mem::align_of::<_opaque_pthread_once_t>() - 8usize];
    ["Offset of field: _opaque_pthread_once_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_once_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlock_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlock_t>() - 200usize];
    ["Alignment of _opaque_pthread_rwlock_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlock_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlockattr_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlockattr_t>() - 24usize];
    ["Alignment of _opaque_pthread_rwlockattr_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_t"][::std::mem::size_of::<_opaque_pthread_t>() - 8192usize];
    ["Alignment of _opaque_pthread_t"][::std::mem::align_of::<_opaque_pthread_t>() - 8usize];
    ["Offset of field: _opaque_pthread_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_t::__cleanup_stack"]
        [::std::mem::offset_of!(_opaque_pthread_t, __cleanup_stack) - 8usize];
    ["Offset of field: _opaque_pthread_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_t, __opaque) - 16usize];
};
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type u_int8_t = ::std::os::raw::c_uchar;
pub type u_int16_t = ::std::os::raw::c_ushort;
pub type u_int32_t = ::std::os::raw::c_uint;
pub type u_int64_t = ::std::os::raw::c_ulonglong;
pub type register_t = i64;
pub type user_addr_t = u_int64_t;
pub type user_size_t = u_int64_t;
pub type user_ssize_t = i64;
pub type user_long_t = i64;
pub type user_ulong_t = u_int64_t;
pub type user_time_t = i64;
pub type user_off_t = i64;
pub type syscall_arg_t = u_int64_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub const SAPP_MAX_TOUCHPOINTS: _bindgen_ty_1 = 8;
pub const SAPP_MAX_MOUSEBUTTONS: _bindgen_ty_1 = 3;
pub const SAPP_MAX_KEYCODES: _bindgen_ty_1 = 512;
pub const SAPP_MAX_ICONIMAGES: _bindgen_ty_1 = 8;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub const sapp_event_type_SAPP_EVENTTYPE_INVALID: sapp_event_type = 0;
pub const sapp_event_type_SAPP_EVENTTYPE_KEY_DOWN: sapp_event_type = 1;
pub const sapp_event_type_SAPP_EVENTTYPE_KEY_UP: sapp_event_type = 2;
pub const sapp_event_type_SAPP_EVENTTYPE_CHAR: sapp_event_type = 3;
pub const sapp_event_type_SAPP_EVENTTYPE_MOUSE_DOWN: sapp_event_type = 4;
pub const sapp_event_type_SAPP_EVENTTYPE_MOUSE_UP: sapp_event_type = 5;
pub const sapp_event_type_SAPP_EVENTTYPE_MOUSE_SCROLL: sapp_event_type = 6;
pub const sapp_event_type_SAPP_EVENTTYPE_MOUSE_MOVE: sapp_event_type = 7;
pub const sapp_event_type_SAPP_EVENTTYPE_MOUSE_ENTER: sapp_event_type = 8;
pub const sapp_event_type_SAPP_EVENTTYPE_MOUSE_LEAVE: sapp_event_type = 9;
pub const sapp_event_type_SAPP_EVENTTYPE_TOUCHES_BEGAN: sapp_event_type = 10;
pub const sapp_event_type_SAPP_EVENTTYPE_TOUCHES_MOVED: sapp_event_type = 11;
pub const sapp_event_type_SAPP_EVENTTYPE_TOUCHES_ENDED: sapp_event_type = 12;
pub const sapp_event_type_SAPP_EVENTTYPE_TOUCHES_CANCELLED: sapp_event_type = 13;
pub const sapp_event_type_SAPP_EVENTTYPE_RESIZED: sapp_event_type = 14;
pub const sapp_event_type_SAPP_EVENTTYPE_ICONIFIED: sapp_event_type = 15;
pub const sapp_event_type_SAPP_EVENTTYPE_RESTORED: sapp_event_type = 16;
pub const sapp_event_type_SAPP_EVENTTYPE_FOCUSED: sapp_event_type = 17;
pub const sapp_event_type_SAPP_EVENTTYPE_UNFOCUSED: sapp_event_type = 18;
pub const sapp_event_type_SAPP_EVENTTYPE_SUSPENDED: sapp_event_type = 19;
pub const sapp_event_type_SAPP_EVENTTYPE_RESUMED: sapp_event_type = 20;
pub const sapp_event_type_SAPP_EVENTTYPE_QUIT_REQUESTED: sapp_event_type = 21;
pub const sapp_event_type_SAPP_EVENTTYPE_CLIPBOARD_PASTED: sapp_event_type = 22;
pub const sapp_event_type_SAPP_EVENTTYPE_FILES_DROPPED: sapp_event_type = 23;
pub const sapp_event_type__SAPP_EVENTTYPE_NUM: sapp_event_type = 24;
pub const sapp_event_type__SAPP_EVENTTYPE_FORCE_U32: sapp_event_type = 2147483647;
pub type sapp_event_type = ::std::os::raw::c_uint;
pub const sapp_keycode_SAPP_KEYCODE_INVALID: sapp_keycode = 0;
pub const sapp_keycode_SAPP_KEYCODE_SPACE: sapp_keycode = 32;
pub const sapp_keycode_SAPP_KEYCODE_APOSTROPHE: sapp_keycode = 39;
pub const sapp_keycode_SAPP_KEYCODE_COMMA: sapp_keycode = 44;
pub const sapp_keycode_SAPP_KEYCODE_MINUS: sapp_keycode = 45;
pub const sapp_keycode_SAPP_KEYCODE_PERIOD: sapp_keycode = 46;
pub const sapp_keycode_SAPP_KEYCODE_SLASH: sapp_keycode = 47;
pub const sapp_keycode_SAPP_KEYCODE_0: sapp_keycode = 48;
pub const sapp_keycode_SAPP_KEYCODE_1: sapp_keycode = 49;
pub const sapp_keycode_SAPP_KEYCODE_2: sapp_keycode = 50;
pub const sapp_keycode_SAPP_KEYCODE_3: sapp_keycode = 51;
pub const sapp_keycode_SAPP_KEYCODE_4: sapp_keycode = 52;
pub const sapp_keycode_SAPP_KEYCODE_5: sapp_keycode = 53;
pub const sapp_keycode_SAPP_KEYCODE_6: sapp_keycode = 54;
pub const sapp_keycode_SAPP_KEYCODE_7: sapp_keycode = 55;
pub const sapp_keycode_SAPP_KEYCODE_8: sapp_keycode = 56;
pub const sapp_keycode_SAPP_KEYCODE_9: sapp_keycode = 57;
pub const sapp_keycode_SAPP_KEYCODE_SEMICOLON: sapp_keycode = 59;
pub const sapp_keycode_SAPP_KEYCODE_EQUAL: sapp_keycode = 61;
pub const sapp_keycode_SAPP_KEYCODE_A: sapp_keycode = 65;
pub const sapp_keycode_SAPP_KEYCODE_B: sapp_keycode = 66;
pub const sapp_keycode_SAPP_KEYCODE_C: sapp_keycode = 67;
pub const sapp_keycode_SAPP_KEYCODE_D: sapp_keycode = 68;
pub const sapp_keycode_SAPP_KEYCODE_E: sapp_keycode = 69;
pub const sapp_keycode_SAPP_KEYCODE_F: sapp_keycode = 70;
pub const sapp_keycode_SAPP_KEYCODE_G: sapp_keycode = 71;
pub const sapp_keycode_SAPP_KEYCODE_H: sapp_keycode = 72;
pub const sapp_keycode_SAPP_KEYCODE_I: sapp_keycode = 73;
pub const sapp_keycode_SAPP_KEYCODE_J: sapp_keycode = 74;
pub const sapp_keycode_SAPP_KEYCODE_K: sapp_keycode = 75;
pub const sapp_keycode_SAPP_KEYCODE_L: sapp_keycode = 76;
pub const sapp_keycode_SAPP_KEYCODE_M: sapp_keycode = 77;
pub const sapp_keycode_SAPP_KEYCODE_N: sapp_keycode = 78;
pub const sapp_keycode_SAPP_KEYCODE_O: sapp_keycode = 79;
pub const sapp_keycode_SAPP_KEYCODE_P: sapp_keycode = 80;
pub const sapp_keycode_SAPP_KEYCODE_Q: sapp_keycode = 81;
pub const sapp_keycode_SAPP_KEYCODE_R: sapp_keycode = 82;
pub const sapp_keycode_SAPP_KEYCODE_S: sapp_keycode = 83;
pub const sapp_keycode_SAPP_KEYCODE_T: sapp_keycode = 84;
pub const sapp_keycode_SAPP_KEYCODE_U: sapp_keycode = 85;
pub const sapp_keycode_SAPP_KEYCODE_V: sapp_keycode = 86;
pub const sapp_keycode_SAPP_KEYCODE_W: sapp_keycode = 87;
pub const sapp_keycode_SAPP_KEYCODE_X: sapp_keycode = 88;
pub const sapp_keycode_SAPP_KEYCODE_Y: sapp_keycode = 89;
pub const sapp_keycode_SAPP_KEYCODE_Z: sapp_keycode = 90;
pub const sapp_keycode_SAPP_KEYCODE_LEFT_BRACKET: sapp_keycode = 91;
pub const sapp_keycode_SAPP_KEYCODE_BACKSLASH: sapp_keycode = 92;
pub const sapp_keycode_SAPP_KEYCODE_RIGHT_BRACKET: sapp_keycode = 93;
pub const sapp_keycode_SAPP_KEYCODE_GRAVE_ACCENT: sapp_keycode = 96;
pub const sapp_keycode_SAPP_KEYCODE_WORLD_1: sapp_keycode = 161;
pub const sapp_keycode_SAPP_KEYCODE_WORLD_2: sapp_keycode = 162;
pub const sapp_keycode_SAPP_KEYCODE_ESCAPE: sapp_keycode = 256;
pub const sapp_keycode_SAPP_KEYCODE_ENTER: sapp_keycode = 257;
pub const sapp_keycode_SAPP_KEYCODE_TAB: sapp_keycode = 258;
pub const sapp_keycode_SAPP_KEYCODE_BACKSPACE: sapp_keycode = 259;
pub const sapp_keycode_SAPP_KEYCODE_INSERT: sapp_keycode = 260;
pub const sapp_keycode_SAPP_KEYCODE_DELETE: sapp_keycode = 261;
pub const sapp_keycode_SAPP_KEYCODE_RIGHT: sapp_keycode = 262;
pub const sapp_keycode_SAPP_KEYCODE_LEFT: sapp_keycode = 263;
pub const sapp_keycode_SAPP_KEYCODE_DOWN: sapp_keycode = 264;
pub const sapp_keycode_SAPP_KEYCODE_UP: sapp_keycode = 265;
pub const sapp_keycode_SAPP_KEYCODE_PAGE_UP: sapp_keycode = 266;
pub const sapp_keycode_SAPP_KEYCODE_PAGE_DOWN: sapp_keycode = 267;
pub const sapp_keycode_SAPP_KEYCODE_HOME: sapp_keycode = 268;
pub const sapp_keycode_SAPP_KEYCODE_END: sapp_keycode = 269;
pub const sapp_keycode_SAPP_KEYCODE_CAPS_LOCK: sapp_keycode = 280;
pub const sapp_keycode_SAPP_KEYCODE_SCROLL_LOCK: sapp_keycode = 281;
pub const sapp_keycode_SAPP_KEYCODE_NUM_LOCK: sapp_keycode = 282;
pub const sapp_keycode_SAPP_KEYCODE_PRINT_SCREEN: sapp_keycode = 283;
pub const sapp_keycode_SAPP_KEYCODE_PAUSE: sapp_keycode = 284;
pub const sapp_keycode_SAPP_KEYCODE_F1: sapp_keycode = 290;
pub const sapp_keycode_SAPP_KEYCODE_F2: sapp_keycode = 291;
pub const sapp_keycode_SAPP_KEYCODE_F3: sapp_keycode = 292;
pub const sapp_keycode_SAPP_KEYCODE_F4: sapp_keycode = 293;
pub const sapp_keycode_SAPP_KEYCODE_F5: sapp_keycode = 294;
pub const sapp_keycode_SAPP_KEYCODE_F6: sapp_keycode = 295;
pub const sapp_keycode_SAPP_KEYCODE_F7: sapp_keycode = 296;
pub const sapp_keycode_SAPP_KEYCODE_F8: sapp_keycode = 297;
pub const sapp_keycode_SAPP_KEYCODE_F9: sapp_keycode = 298;
pub const sapp_keycode_SAPP_KEYCODE_F10: sapp_keycode = 299;
pub const sapp_keycode_SAPP_KEYCODE_F11: sapp_keycode = 300;
pub const sapp_keycode_SAPP_KEYCODE_F12: sapp_keycode = 301;
pub const sapp_keycode_SAPP_KEYCODE_F13: sapp_keycode = 302;
pub const sapp_keycode_SAPP_KEYCODE_F14: sapp_keycode = 303;
pub const sapp_keycode_SAPP_KEYCODE_F15: sapp_keycode = 304;
pub const sapp_keycode_SAPP_KEYCODE_F16: sapp_keycode = 305;
pub const sapp_keycode_SAPP_KEYCODE_F17: sapp_keycode = 306;
pub const sapp_keycode_SAPP_KEYCODE_F18: sapp_keycode = 307;
pub const sapp_keycode_SAPP_KEYCODE_F19: sapp_keycode = 308;
pub const sapp_keycode_SAPP_KEYCODE_F20: sapp_keycode = 309;
pub const sapp_keycode_SAPP_KEYCODE_F21: sapp_keycode = 310;
pub const sapp_keycode_SAPP_KEYCODE_F22: sapp_keycode = 311;
pub const sapp_keycode_SAPP_KEYCODE_F23: sapp_keycode = 312;
pub const sapp_keycode_SAPP_KEYCODE_F24: sapp_keycode = 313;
pub const sapp_keycode_SAPP_KEYCODE_F25: sapp_keycode = 314;
pub const sapp_keycode_SAPP_KEYCODE_KP_0: sapp_keycode = 320;
pub const sapp_keycode_SAPP_KEYCODE_KP_1: sapp_keycode = 321;
pub const sapp_keycode_SAPP_KEYCODE_KP_2: sapp_keycode = 322;
pub const sapp_keycode_SAPP_KEYCODE_KP_3: sapp_keycode = 323;
pub const sapp_keycode_SAPP_KEYCODE_KP_4: sapp_keycode = 324;
pub const sapp_keycode_SAPP_KEYCODE_KP_5: sapp_keycode = 325;
pub const sapp_keycode_SAPP_KEYCODE_KP_6: sapp_keycode = 326;
pub const sapp_keycode_SAPP_KEYCODE_KP_7: sapp_keycode = 327;
pub const sapp_keycode_SAPP_KEYCODE_KP_8: sapp_keycode = 328;
pub const sapp_keycode_SAPP_KEYCODE_KP_9: sapp_keycode = 329;
pub const sapp_keycode_SAPP_KEYCODE_KP_DECIMAL: sapp_keycode = 330;
pub const sapp_keycode_SAPP_KEYCODE_KP_DIVIDE: sapp_keycode = 331;
pub const sapp_keycode_SAPP_KEYCODE_KP_MULTIPLY: sapp_keycode = 332;
pub const sapp_keycode_SAPP_KEYCODE_KP_SUBTRACT: sapp_keycode = 333;
pub const sapp_keycode_SAPP_KEYCODE_KP_ADD: sapp_keycode = 334;
pub const sapp_keycode_SAPP_KEYCODE_KP_ENTER: sapp_keycode = 335;
pub const sapp_keycode_SAPP_KEYCODE_KP_EQUAL: sapp_keycode = 336;
pub const sapp_keycode_SAPP_KEYCODE_LEFT_SHIFT: sapp_keycode = 340;
pub const sapp_keycode_SAPP_KEYCODE_LEFT_CONTROL: sapp_keycode = 341;
pub const sapp_keycode_SAPP_KEYCODE_LEFT_ALT: sapp_keycode = 342;
pub const sapp_keycode_SAPP_KEYCODE_LEFT_SUPER: sapp_keycode = 343;
pub const sapp_keycode_SAPP_KEYCODE_RIGHT_SHIFT: sapp_keycode = 344;
pub const sapp_keycode_SAPP_KEYCODE_RIGHT_CONTROL: sapp_keycode = 345;
pub const sapp_keycode_SAPP_KEYCODE_RIGHT_ALT: sapp_keycode = 346;
pub const sapp_keycode_SAPP_KEYCODE_RIGHT_SUPER: sapp_keycode = 347;
pub const sapp_keycode_SAPP_KEYCODE_MENU: sapp_keycode = 348;
pub type sapp_keycode = ::std::os::raw::c_uint;
pub const sapp_android_tooltype_SAPP_ANDROIDTOOLTYPE_UNKNOWN: sapp_android_tooltype = 0;
pub const sapp_android_tooltype_SAPP_ANDROIDTOOLTYPE_FINGER: sapp_android_tooltype = 1;
pub const sapp_android_tooltype_SAPP_ANDROIDTOOLTYPE_STYLUS: sapp_android_tooltype = 2;
pub const sapp_android_tooltype_SAPP_ANDROIDTOOLTYPE_MOUSE: sapp_android_tooltype = 3;
pub type sapp_android_tooltype = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_touchpoint {
    pub identifier: usize,
    pub pos_x: f32,
    pub pos_y: f32,
    pub android_tooltype: sapp_android_tooltype,
    pub changed: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_touchpoint"][::std::mem::size_of::<sapp_touchpoint>() - 24usize];
    ["Alignment of sapp_touchpoint"][::std::mem::align_of::<sapp_touchpoint>() - 8usize];
    ["Offset of field: sapp_touchpoint::identifier"]
        [::std::mem::offset_of!(sapp_touchpoint, identifier) - 0usize];
    ["Offset of field: sapp_touchpoint::pos_x"]
        [::std::mem::offset_of!(sapp_touchpoint, pos_x) - 8usize];
    ["Offset of field: sapp_touchpoint::pos_y"]
        [::std::mem::offset_of!(sapp_touchpoint, pos_y) - 12usize];
    ["Offset of field: sapp_touchpoint::android_tooltype"]
        [::std::mem::offset_of!(sapp_touchpoint, android_tooltype) - 16usize];
    ["Offset of field: sapp_touchpoint::changed"]
        [::std::mem::offset_of!(sapp_touchpoint, changed) - 20usize];
};
pub const sapp_mousebutton_SAPP_MOUSEBUTTON_LEFT: sapp_mousebutton = 0;
pub const sapp_mousebutton_SAPP_MOUSEBUTTON_RIGHT: sapp_mousebutton = 1;
pub const sapp_mousebutton_SAPP_MOUSEBUTTON_MIDDLE: sapp_mousebutton = 2;
pub const sapp_mousebutton_SAPP_MOUSEBUTTON_INVALID: sapp_mousebutton = 256;
pub type sapp_mousebutton = ::std::os::raw::c_uint;
pub const SAPP_MODIFIER_SHIFT: _bindgen_ty_2 = 1;
pub const SAPP_MODIFIER_CTRL: _bindgen_ty_2 = 2;
pub const SAPP_MODIFIER_ALT: _bindgen_ty_2 = 4;
pub const SAPP_MODIFIER_SUPER: _bindgen_ty_2 = 8;
pub const SAPP_MODIFIER_LMB: _bindgen_ty_2 = 256;
pub const SAPP_MODIFIER_RMB: _bindgen_ty_2 = 512;
pub const SAPP_MODIFIER_MMB: _bindgen_ty_2 = 1024;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_event {
    pub frame_count: u64,
    pub type_: sapp_event_type,
    pub key_code: sapp_keycode,
    pub char_code: u32,
    pub key_repeat: bool,
    pub modifiers: u32,
    pub mouse_button: sapp_mousebutton,
    pub mouse_x: f32,
    pub mouse_y: f32,
    pub mouse_dx: f32,
    pub mouse_dy: f32,
    pub scroll_x: f32,
    pub scroll_y: f32,
    pub num_touches: ::std::os::raw::c_int,
    pub touches: [sapp_touchpoint; 8usize],
    pub window_width: ::std::os::raw::c_int,
    pub window_height: ::std::os::raw::c_int,
    pub framebuffer_width: ::std::os::raw::c_int,
    pub framebuffer_height: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_event"][::std::mem::size_of::<sapp_event>() - 272usize];
    ["Alignment of sapp_event"][::std::mem::align_of::<sapp_event>() - 8usize];
    ["Offset of field: sapp_event::frame_count"]
        [::std::mem::offset_of!(sapp_event, frame_count) - 0usize];
    ["Offset of field: sapp_event::type_"][::std::mem::offset_of!(sapp_event, type_) - 8usize];
    ["Offset of field: sapp_event::key_code"]
        [::std::mem::offset_of!(sapp_event, key_code) - 12usize];
    ["Offset of field: sapp_event::char_code"]
        [::std::mem::offset_of!(sapp_event, char_code) - 16usize];
    ["Offset of field: sapp_event::key_repeat"]
        [::std::mem::offset_of!(sapp_event, key_repeat) - 20usize];
    ["Offset of field: sapp_event::modifiers"]
        [::std::mem::offset_of!(sapp_event, modifiers) - 24usize];
    ["Offset of field: sapp_event::mouse_button"]
        [::std::mem::offset_of!(sapp_event, mouse_button) - 28usize];
    ["Offset of field: sapp_event::mouse_x"][::std::mem::offset_of!(sapp_event, mouse_x) - 32usize];
    ["Offset of field: sapp_event::mouse_y"][::std::mem::offset_of!(sapp_event, mouse_y) - 36usize];
    ["Offset of field: sapp_event::mouse_dx"]
        [::std::mem::offset_of!(sapp_event, mouse_dx) - 40usize];
    ["Offset of field: sapp_event::mouse_dy"]
        [::std::mem::offset_of!(sapp_event, mouse_dy) - 44usize];
    ["Offset of field: sapp_event::scroll_x"]
        [::std::mem::offset_of!(sapp_event, scroll_x) - 48usize];
    ["Offset of field: sapp_event::scroll_y"]
        [::std::mem::offset_of!(sapp_event, scroll_y) - 52usize];
    ["Offset of field: sapp_event::num_touches"]
        [::std::mem::offset_of!(sapp_event, num_touches) - 56usize];
    ["Offset of field: sapp_event::touches"][::std::mem::offset_of!(sapp_event, touches) - 64usize];
    ["Offset of field: sapp_event::window_width"]
        [::std::mem::offset_of!(sapp_event, window_width) - 256usize];
    ["Offset of field: sapp_event::window_height"]
        [::std::mem::offset_of!(sapp_event, window_height) - 260usize];
    ["Offset of field: sapp_event::framebuffer_width"]
        [::std::mem::offset_of!(sapp_event, framebuffer_width) - 264usize];
    ["Offset of field: sapp_event::framebuffer_height"]
        [::std::mem::offset_of!(sapp_event, framebuffer_height) - 268usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_range {
    pub ptr: *const ::std::os::raw::c_void,
    pub size: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_range"][::std::mem::size_of::<sapp_range>() - 16usize];
    ["Alignment of sapp_range"][::std::mem::align_of::<sapp_range>() - 8usize];
    ["Offset of field: sapp_range::ptr"][::std::mem::offset_of!(sapp_range, ptr) - 0usize];
    ["Offset of field: sapp_range::size"][::std::mem::offset_of!(sapp_range, size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_image_desc {
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub cursor_hotspot_x: ::std::os::raw::c_int,
    pub cursor_hotspot_y: ::std::os::raw::c_int,
    pub pixels: sapp_range,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_image_desc"][::std::mem::size_of::<sapp_image_desc>() - 32usize];
    ["Alignment of sapp_image_desc"][::std::mem::align_of::<sapp_image_desc>() - 8usize];
    ["Offset of field: sapp_image_desc::width"]
        [::std::mem::offset_of!(sapp_image_desc, width) - 0usize];
    ["Offset of field: sapp_image_desc::height"]
        [::std::mem::offset_of!(sapp_image_desc, height) - 4usize];
    ["Offset of field: sapp_image_desc::cursor_hotspot_x"]
        [::std::mem::offset_of!(sapp_image_desc, cursor_hotspot_x) - 8usize];
    ["Offset of field: sapp_image_desc::cursor_hotspot_y"]
        [::std::mem::offset_of!(sapp_image_desc, cursor_hotspot_y) - 12usize];
    ["Offset of field: sapp_image_desc::pixels"]
        [::std::mem::offset_of!(sapp_image_desc, pixels) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_icon_desc {
    pub sokol_default: bool,
    pub images: [sapp_image_desc; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_icon_desc"][::std::mem::size_of::<sapp_icon_desc>() - 264usize];
    ["Alignment of sapp_icon_desc"][::std::mem::align_of::<sapp_icon_desc>() - 8usize];
    ["Offset of field: sapp_icon_desc::sokol_default"]
        [::std::mem::offset_of!(sapp_icon_desc, sokol_default) - 0usize];
    ["Offset of field: sapp_icon_desc::images"]
        [::std::mem::offset_of!(sapp_icon_desc, images) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_allocator {
    pub alloc_fn: ::std::option::Option<
        unsafe extern "C" fn(
            size: usize,
            user_data: *mut ::std::os::raw::c_void,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub free_fn: ::std::option::Option<
        unsafe extern "C" fn(
            ptr: *mut ::std::os::raw::c_void,
            user_data: *mut ::std::os::raw::c_void,
        ),
    >,
    pub user_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_allocator"][::std::mem::size_of::<sapp_allocator>() - 24usize];
    ["Alignment of sapp_allocator"][::std::mem::align_of::<sapp_allocator>() - 8usize];
    ["Offset of field: sapp_allocator::alloc_fn"]
        [::std::mem::offset_of!(sapp_allocator, alloc_fn) - 0usize];
    ["Offset of field: sapp_allocator::free_fn"]
        [::std::mem::offset_of!(sapp_allocator, free_fn) - 8usize];
    ["Offset of field: sapp_allocator::user_data"]
        [::std::mem::offset_of!(sapp_allocator, user_data) - 16usize];
};
pub const sapp_log_item_SAPP_LOGITEM_OK: sapp_log_item = 0;
pub const sapp_log_item_SAPP_LOGITEM_MALLOC_FAILED: sapp_log_item = 1;
pub const sapp_log_item_SAPP_LOGITEM_MACOS_INVALID_NSOPENGL_PROFILE: sapp_log_item = 2;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_LOAD_OPENGL32_DLL_FAILED: sapp_log_item = 3;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_CREATE_HELPER_WINDOW_FAILED: sapp_log_item = 4;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_HELPER_WINDOW_GETDC_FAILED: sapp_log_item = 5;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_DUMMY_CONTEXT_SET_PIXELFORMAT_FAILED: sapp_log_item = 6;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_CREATE_DUMMY_CONTEXT_FAILED: sapp_log_item = 7;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_DUMMY_CONTEXT_MAKE_CURRENT_FAILED: sapp_log_item = 8;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_GET_PIXELFORMAT_ATTRIB_FAILED: sapp_log_item = 9;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_FIND_PIXELFORMAT_FAILED: sapp_log_item = 10;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_DESCRIBE_PIXELFORMAT_FAILED: sapp_log_item = 11;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_SET_PIXELFORMAT_FAILED: sapp_log_item = 12;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_ARB_CREATE_CONTEXT_REQUIRED: sapp_log_item = 13;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_ARB_CREATE_CONTEXT_PROFILE_REQUIRED: sapp_log_item =
    14;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_OPENGL_VERSION_NOT_SUPPORTED: sapp_log_item = 15;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_OPENGL_PROFILE_NOT_SUPPORTED: sapp_log_item = 16;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_INCOMPATIBLE_DEVICE_CONTEXT: sapp_log_item = 17;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_WGL_CREATE_CONTEXT_ATTRIBS_FAILED_OTHER: sapp_log_item =
    18;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_D3D11_CREATE_DEVICE_AND_SWAPCHAIN_WITH_DEBUG_FAILED:
    sapp_log_item = 19;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_D3D11_GET_IDXGIFACTORY_FAILED: sapp_log_item = 20;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_D3D11_GET_IDXGIADAPTER_FAILED: sapp_log_item = 21;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_D3D11_QUERY_INTERFACE_IDXGIDEVICE1_FAILED:
    sapp_log_item = 22;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_REGISTER_RAW_INPUT_DEVICES_FAILED_MOUSE_LOCK:
    sapp_log_item = 23;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_REGISTER_RAW_INPUT_DEVICES_FAILED_MOUSE_UNLOCK:
    sapp_log_item = 24;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_GET_RAW_INPUT_DATA_FAILED: sapp_log_item = 25;
pub const sapp_log_item_SAPP_LOGITEM_WIN32_DESTROYICON_FOR_CURSOR_FAILED: sapp_log_item = 26;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_LOAD_LIBGL_FAILED: sapp_log_item = 27;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_LOAD_ENTRY_POINTS_FAILED: sapp_log_item = 28;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_EXTENSION_NOT_FOUND: sapp_log_item = 29;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_QUERY_VERSION_FAILED: sapp_log_item = 30;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_VERSION_TOO_LOW: sapp_log_item = 31;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_NO_GLXFBCONFIGS: sapp_log_item = 32;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_NO_SUITABLE_GLXFBCONFIG: sapp_log_item = 33;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_GET_VISUAL_FROM_FBCONFIG_FAILED: sapp_log_item = 34;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_REQUIRED_EXTENSIONS_MISSING: sapp_log_item = 35;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_CREATE_CONTEXT_FAILED: sapp_log_item = 36;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_GLX_CREATE_WINDOW_FAILED: sapp_log_item = 37;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_X11_CREATE_WINDOW_FAILED: sapp_log_item = 38;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_BIND_OPENGL_API_FAILED: sapp_log_item = 39;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_BIND_OPENGL_ES_API_FAILED: sapp_log_item = 40;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_GET_DISPLAY_FAILED: sapp_log_item = 41;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_INITIALIZE_FAILED: sapp_log_item = 42;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_NO_CONFIGS: sapp_log_item = 43;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_NO_NATIVE_VISUAL: sapp_log_item = 44;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_GET_VISUAL_INFO_FAILED: sapp_log_item = 45;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_CREATE_WINDOW_SURFACE_FAILED: sapp_log_item = 46;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_CREATE_CONTEXT_FAILED: sapp_log_item = 47;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_EGL_MAKE_CURRENT_FAILED: sapp_log_item = 48;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_X11_OPEN_DISPLAY_FAILED: sapp_log_item = 49;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_X11_QUERY_SYSTEM_DPI_FAILED: sapp_log_item = 50;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_X11_DROPPED_FILE_URI_WRONG_SCHEME: sapp_log_item = 51;
pub const sapp_log_item_SAPP_LOGITEM_LINUX_X11_FAILED_TO_BECOME_OWNER_OF_CLIPBOARD: sapp_log_item =
    52;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_UNSUPPORTED_INPUT_EVENT_INPUT_CB: sapp_log_item = 53;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_UNSUPPORTED_INPUT_EVENT_MAIN_CB: sapp_log_item = 54;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_READ_MSG_FAILED: sapp_log_item = 55;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_WRITE_MSG_FAILED: sapp_log_item = 56;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_CREATE: sapp_log_item = 57;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_RESUME: sapp_log_item = 58;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_PAUSE: sapp_log_item = 59;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_FOCUS: sapp_log_item = 60;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_NO_FOCUS: sapp_log_item = 61;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_SET_NATIVE_WINDOW: sapp_log_item = 62;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_SET_INPUT_QUEUE: sapp_log_item = 63;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_MSG_DESTROY: sapp_log_item = 64;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_UNKNOWN_MSG: sapp_log_item = 65;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_LOOP_THREAD_STARTED: sapp_log_item = 66;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_LOOP_THREAD_DONE: sapp_log_item = 67;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONSTART: sapp_log_item = 68;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONRESUME: sapp_log_item = 69;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONSAVEINSTANCESTATE: sapp_log_item =
    70;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONWINDOWFOCUSCHANGED: sapp_log_item =
    71;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONPAUSE: sapp_log_item = 72;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONSTOP: sapp_log_item = 73;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONNATIVEWINDOWCREATED: sapp_log_item =
    74;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONNATIVEWINDOWDESTROYED:
    sapp_log_item = 75;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONINPUTQUEUECREATED: sapp_log_item =
    76;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONINPUTQUEUEDESTROYED: sapp_log_item =
    77;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONCONFIGURATIONCHANGED: sapp_log_item =
    78;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONLOWMEMORY: sapp_log_item = 79;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONDESTROY: sapp_log_item = 80;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_DONE: sapp_log_item = 81;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_ONCREATE: sapp_log_item = 82;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_CREATE_THREAD_PIPE_FAILED: sapp_log_item = 83;
pub const sapp_log_item_SAPP_LOGITEM_ANDROID_NATIVE_ACTIVITY_CREATE_SUCCESS: sapp_log_item = 84;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_DEVICE_LOST: sapp_log_item = 85;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_DEVICE_LOG: sapp_log_item = 86;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_DEVICE_UNCAPTURED_ERROR: sapp_log_item = 87;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_CREATE_SURFACE_FAILED: sapp_log_item = 88;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_SURFACE_GET_CAPABILITIES_FAILED: sapp_log_item =
    89;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_CREATE_DEPTH_STENCIL_TEXTURE_FAILED:
    sapp_log_item = 90;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_CREATE_DEPTH_STENCIL_VIEW_FAILED:
    sapp_log_item = 91;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_CREATE_MSAA_TEXTURE_FAILED: sapp_log_item = 92;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_CREATE_MSAA_VIEW_FAILED: sapp_log_item = 93;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_SWAPCHAIN_GETCURRENTTEXTURE_FAILED: sapp_log_item = 94;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_REQUEST_DEVICE_STATUS_ERROR: sapp_log_item = 95;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_REQUEST_DEVICE_STATUS_UNKNOWN: sapp_log_item = 96;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_REQUEST_ADAPTER_STATUS_UNAVAILABLE: sapp_log_item = 97;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_REQUEST_ADAPTER_STATUS_ERROR: sapp_log_item = 98;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_REQUEST_ADAPTER_STATUS_UNKNOWN: sapp_log_item = 99;
pub const sapp_log_item_SAPP_LOGITEM_WGPU_CREATE_INSTANCE_FAILED: sapp_log_item = 100;
pub const sapp_log_item_SAPP_LOGITEM_IMAGE_DATA_SIZE_MISMATCH: sapp_log_item = 101;
pub const sapp_log_item_SAPP_LOGITEM_DROPPED_FILE_PATH_TOO_LONG: sapp_log_item = 102;
pub const sapp_log_item_SAPP_LOGITEM_CLIPBOARD_STRING_TOO_BIG: sapp_log_item = 103;
pub type sapp_log_item = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_logger {
    pub func: ::std::option::Option<
        unsafe extern "C" fn(
            tag: *const ::std::os::raw::c_char,
            log_level: u32,
            log_item_id: u32,
            message_or_null: *const ::std::os::raw::c_char,
            line_nr: u32,
            filename_or_null: *const ::std::os::raw::c_char,
            user_data: *mut ::std::os::raw::c_void,
        ),
    >,
    pub user_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_logger"][::std::mem::size_of::<sapp_logger>() - 16usize];
    ["Alignment of sapp_logger"][::std::mem::align_of::<sapp_logger>() - 8usize];
    ["Offset of field: sapp_logger::func"][::std::mem::offset_of!(sapp_logger, func) - 0usize];
    ["Offset of field: sapp_logger::user_data"]
        [::std::mem::offset_of!(sapp_logger, user_data) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_desc {
    pub init_cb: ::std::option::Option<unsafe extern "C" fn()>,
    pub frame_cb: ::std::option::Option<unsafe extern "C" fn()>,
    pub cleanup_cb: ::std::option::Option<unsafe extern "C" fn()>,
    pub event_cb: ::std::option::Option<unsafe extern "C" fn(arg1: *const sapp_event)>,
    pub user_data: *mut ::std::os::raw::c_void,
    pub init_userdata_cb:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub frame_userdata_cb:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub cleanup_userdata_cb:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub event_userdata_cb: ::std::option::Option<
        unsafe extern "C" fn(arg1: *const sapp_event, arg2: *mut ::std::os::raw::c_void),
    >,
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub sample_count: ::std::os::raw::c_int,
    pub swap_interval: ::std::os::raw::c_int,
    pub high_dpi: bool,
    pub fullscreen: bool,
    pub alpha: bool,
    pub window_title: *const ::std::os::raw::c_char,
    pub enable_clipboard: bool,
    pub clipboard_size: ::std::os::raw::c_int,
    pub enable_dragndrop: bool,
    pub max_dropped_files: ::std::os::raw::c_int,
    pub max_dropped_file_path_length: ::std::os::raw::c_int,
    pub icon: sapp_icon_desc,
    pub allocator: sapp_allocator,
    pub logger: sapp_logger,
    pub gl_major_version: ::std::os::raw::c_int,
    pub gl_minor_version: ::std::os::raw::c_int,
    pub win32_console_utf8: bool,
    pub win32_console_create: bool,
    pub win32_console_attach: bool,
    pub html5_canvas_selector: *const ::std::os::raw::c_char,
    pub html5_canvas_resize: bool,
    pub html5_preserve_drawing_buffer: bool,
    pub html5_premultiplied_alpha: bool,
    pub html5_ask_leave_site: bool,
    pub html5_update_document_title: bool,
    pub html5_bubble_mouse_events: bool,
    pub html5_bubble_touch_events: bool,
    pub html5_bubble_wheel_events: bool,
    pub html5_bubble_key_events: bool,
    pub html5_bubble_char_events: bool,
    pub html5_use_emsc_set_main_loop: bool,
    pub html5_emsc_set_main_loop_simulate_infinite_loop: bool,
    pub ios_keyboard_resizes_canvas: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_desc"][::std::mem::size_of::<sapp_desc>() - 472usize];
    ["Alignment of sapp_desc"][::std::mem::align_of::<sapp_desc>() - 8usize];
    ["Offset of field: sapp_desc::init_cb"][::std::mem::offset_of!(sapp_desc, init_cb) - 0usize];
    ["Offset of field: sapp_desc::frame_cb"][::std::mem::offset_of!(sapp_desc, frame_cb) - 8usize];
    ["Offset of field: sapp_desc::cleanup_cb"]
        [::std::mem::offset_of!(sapp_desc, cleanup_cb) - 16usize];
    ["Offset of field: sapp_desc::event_cb"][::std::mem::offset_of!(sapp_desc, event_cb) - 24usize];
    ["Offset of field: sapp_desc::user_data"]
        [::std::mem::offset_of!(sapp_desc, user_data) - 32usize];
    ["Offset of field: sapp_desc::init_userdata_cb"]
        [::std::mem::offset_of!(sapp_desc, init_userdata_cb) - 40usize];
    ["Offset of field: sapp_desc::frame_userdata_cb"]
        [::std::mem::offset_of!(sapp_desc, frame_userdata_cb) - 48usize];
    ["Offset of field: sapp_desc::cleanup_userdata_cb"]
        [::std::mem::offset_of!(sapp_desc, cleanup_userdata_cb) - 56usize];
    ["Offset of field: sapp_desc::event_userdata_cb"]
        [::std::mem::offset_of!(sapp_desc, event_userdata_cb) - 64usize];
    ["Offset of field: sapp_desc::width"][::std::mem::offset_of!(sapp_desc, width) - 72usize];
    ["Offset of field: sapp_desc::height"][::std::mem::offset_of!(sapp_desc, height) - 76usize];
    ["Offset of field: sapp_desc::sample_count"]
        [::std::mem::offset_of!(sapp_desc, sample_count) - 80usize];
    ["Offset of field: sapp_desc::swap_interval"]
        [::std::mem::offset_of!(sapp_desc, swap_interval) - 84usize];
    ["Offset of field: sapp_desc::high_dpi"][::std::mem::offset_of!(sapp_desc, high_dpi) - 88usize];
    ["Offset of field: sapp_desc::fullscreen"]
        [::std::mem::offset_of!(sapp_desc, fullscreen) - 89usize];
    ["Offset of field: sapp_desc::alpha"][::std::mem::offset_of!(sapp_desc, alpha) - 90usize];
    ["Offset of field: sapp_desc::window_title"]
        [::std::mem::offset_of!(sapp_desc, window_title) - 96usize];
    ["Offset of field: sapp_desc::enable_clipboard"]
        [::std::mem::offset_of!(sapp_desc, enable_clipboard) - 104usize];
    ["Offset of field: sapp_desc::clipboard_size"]
        [::std::mem::offset_of!(sapp_desc, clipboard_size) - 108usize];
    ["Offset of field: sapp_desc::enable_dragndrop"]
        [::std::mem::offset_of!(sapp_desc, enable_dragndrop) - 112usize];
    ["Offset of field: sapp_desc::max_dropped_files"]
        [::std::mem::offset_of!(sapp_desc, max_dropped_files) - 116usize];
    ["Offset of field: sapp_desc::max_dropped_file_path_length"]
        [::std::mem::offset_of!(sapp_desc, max_dropped_file_path_length) - 120usize];
    ["Offset of field: sapp_desc::icon"][::std::mem::offset_of!(sapp_desc, icon) - 128usize];
    ["Offset of field: sapp_desc::allocator"]
        [::std::mem::offset_of!(sapp_desc, allocator) - 392usize];
    ["Offset of field: sapp_desc::logger"][::std::mem::offset_of!(sapp_desc, logger) - 416usize];
    ["Offset of field: sapp_desc::gl_major_version"]
        [::std::mem::offset_of!(sapp_desc, gl_major_version) - 432usize];
    ["Offset of field: sapp_desc::gl_minor_version"]
        [::std::mem::offset_of!(sapp_desc, gl_minor_version) - 436usize];
    ["Offset of field: sapp_desc::win32_console_utf8"]
        [::std::mem::offset_of!(sapp_desc, win32_console_utf8) - 440usize];
    ["Offset of field: sapp_desc::win32_console_create"]
        [::std::mem::offset_of!(sapp_desc, win32_console_create) - 441usize];
    ["Offset of field: sapp_desc::win32_console_attach"]
        [::std::mem::offset_of!(sapp_desc, win32_console_attach) - 442usize];
    ["Offset of field: sapp_desc::html5_canvas_selector"]
        [::std::mem::offset_of!(sapp_desc, html5_canvas_selector) - 448usize];
    ["Offset of field: sapp_desc::html5_canvas_resize"]
        [::std::mem::offset_of!(sapp_desc, html5_canvas_resize) - 456usize];
    ["Offset of field: sapp_desc::html5_preserve_drawing_buffer"]
        [::std::mem::offset_of!(sapp_desc, html5_preserve_drawing_buffer) - 457usize];
    ["Offset of field: sapp_desc::html5_premultiplied_alpha"]
        [::std::mem::offset_of!(sapp_desc, html5_premultiplied_alpha) - 458usize];
    ["Offset of field: sapp_desc::html5_ask_leave_site"]
        [::std::mem::offset_of!(sapp_desc, html5_ask_leave_site) - 459usize];
    ["Offset of field: sapp_desc::html5_update_document_title"]
        [::std::mem::offset_of!(sapp_desc, html5_update_document_title) - 460usize];
    ["Offset of field: sapp_desc::html5_bubble_mouse_events"]
        [::std::mem::offset_of!(sapp_desc, html5_bubble_mouse_events) - 461usize];
    ["Offset of field: sapp_desc::html5_bubble_touch_events"]
        [::std::mem::offset_of!(sapp_desc, html5_bubble_touch_events) - 462usize];
    ["Offset of field: sapp_desc::html5_bubble_wheel_events"]
        [::std::mem::offset_of!(sapp_desc, html5_bubble_wheel_events) - 463usize];
    ["Offset of field: sapp_desc::html5_bubble_key_events"]
        [::std::mem::offset_of!(sapp_desc, html5_bubble_key_events) - 464usize];
    ["Offset of field: sapp_desc::html5_bubble_char_events"]
        [::std::mem::offset_of!(sapp_desc, html5_bubble_char_events) - 465usize];
    ["Offset of field: sapp_desc::html5_use_emsc_set_main_loop"]
        [::std::mem::offset_of!(sapp_desc, html5_use_emsc_set_main_loop) - 466usize];
    ["Offset of field: sapp_desc::html5_emsc_set_main_loop_simulate_infinite_loop"][::std::mem::offset_of!(
        sapp_desc,
        html5_emsc_set_main_loop_simulate_infinite_loop
    ) - 467usize];
    ["Offset of field: sapp_desc::ios_keyboard_resizes_canvas"]
        [::std::mem::offset_of!(sapp_desc, ios_keyboard_resizes_canvas) - 468usize];
};
pub const sapp_html5_fetch_error_SAPP_HTML5_FETCH_ERROR_NO_ERROR: sapp_html5_fetch_error = 0;
pub const sapp_html5_fetch_error_SAPP_HTML5_FETCH_ERROR_BUFFER_TOO_SMALL: sapp_html5_fetch_error =
    1;
pub const sapp_html5_fetch_error_SAPP_HTML5_FETCH_ERROR_OTHER: sapp_html5_fetch_error = 2;
pub type sapp_html5_fetch_error = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_html5_fetch_response {
    pub succeeded: bool,
    pub error_code: sapp_html5_fetch_error,
    pub file_index: ::std::os::raw::c_int,
    pub data: sapp_range,
    pub buffer: sapp_range,
    pub user_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_html5_fetch_response"]
        [::std::mem::size_of::<sapp_html5_fetch_response>() - 56usize];
    ["Alignment of sapp_html5_fetch_response"]
        [::std::mem::align_of::<sapp_html5_fetch_response>() - 8usize];
    ["Offset of field: sapp_html5_fetch_response::succeeded"]
        [::std::mem::offset_of!(sapp_html5_fetch_response, succeeded) - 0usize];
    ["Offset of field: sapp_html5_fetch_response::error_code"]
        [::std::mem::offset_of!(sapp_html5_fetch_response, error_code) - 4usize];
    ["Offset of field: sapp_html5_fetch_response::file_index"]
        [::std::mem::offset_of!(sapp_html5_fetch_response, file_index) - 8usize];
    ["Offset of field: sapp_html5_fetch_response::data"]
        [::std::mem::offset_of!(sapp_html5_fetch_response, data) - 16usize];
    ["Offset of field: sapp_html5_fetch_response::buffer"]
        [::std::mem::offset_of!(sapp_html5_fetch_response, buffer) - 32usize];
    ["Offset of field: sapp_html5_fetch_response::user_data"]
        [::std::mem::offset_of!(sapp_html5_fetch_response, user_data) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sapp_html5_fetch_request {
    pub dropped_file_index: ::std::os::raw::c_int,
    pub callback:
        ::std::option::Option<unsafe extern "C" fn(arg1: *const sapp_html5_fetch_response)>,
    pub buffer: sapp_range,
    pub user_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sapp_html5_fetch_request"]
        [::std::mem::size_of::<sapp_html5_fetch_request>() - 40usize];
    ["Alignment of sapp_html5_fetch_request"]
        [::std::mem::align_of::<sapp_html5_fetch_request>() - 8usize];
    ["Offset of field: sapp_html5_fetch_request::dropped_file_index"]
        [::std::mem::offset_of!(sapp_html5_fetch_request, dropped_file_index) - 0usize];
    ["Offset of field: sapp_html5_fetch_request::callback"]
        [::std::mem::offset_of!(sapp_html5_fetch_request, callback) - 8usize];
    ["Offset of field: sapp_html5_fetch_request::buffer"]
        [::std::mem::offset_of!(sapp_html5_fetch_request, buffer) - 16usize];
    ["Offset of field: sapp_html5_fetch_request::user_data"]
        [::std::mem::offset_of!(sapp_html5_fetch_request, user_data) - 32usize];
};
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_DEFAULT: sapp_mouse_cursor = 0;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_ARROW: sapp_mouse_cursor = 1;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_IBEAM: sapp_mouse_cursor = 2;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CROSSHAIR: sapp_mouse_cursor = 3;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_POINTING_HAND: sapp_mouse_cursor = 4;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_RESIZE_EW: sapp_mouse_cursor = 5;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_RESIZE_NS: sapp_mouse_cursor = 6;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_RESIZE_NWSE: sapp_mouse_cursor = 7;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_RESIZE_NESW: sapp_mouse_cursor = 8;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_RESIZE_ALL: sapp_mouse_cursor = 9;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_NOT_ALLOWED: sapp_mouse_cursor = 10;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_0: sapp_mouse_cursor = 11;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_1: sapp_mouse_cursor = 12;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_2: sapp_mouse_cursor = 13;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_3: sapp_mouse_cursor = 14;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_4: sapp_mouse_cursor = 15;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_5: sapp_mouse_cursor = 16;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_6: sapp_mouse_cursor = 17;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_7: sapp_mouse_cursor = 18;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_8: sapp_mouse_cursor = 19;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_9: sapp_mouse_cursor = 20;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_10: sapp_mouse_cursor = 21;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_11: sapp_mouse_cursor = 22;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_12: sapp_mouse_cursor = 23;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_13: sapp_mouse_cursor = 24;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_14: sapp_mouse_cursor = 25;
pub const sapp_mouse_cursor_SAPP_MOUSECURSOR_CUSTOM_15: sapp_mouse_cursor = 26;
pub const sapp_mouse_cursor__SAPP_MOUSECURSOR_NUM: sapp_mouse_cursor = 27;
pub type sapp_mouse_cursor = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn sokol_main(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> sapp_desc;
}
unsafe extern "C" {
    pub fn sapp_isvalid() -> bool;
}
unsafe extern "C" {
    pub fn sapp_width() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_widthf() -> f32;
}
unsafe extern "C" {
    pub fn sapp_height() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_heightf() -> f32;
}
unsafe extern "C" {
    pub fn sapp_color_format() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_depth_format() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_sample_count() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_high_dpi() -> bool;
}
unsafe extern "C" {
    pub fn sapp_dpi_scale() -> f32;
}
unsafe extern "C" {
    pub fn sapp_show_keyboard(show: bool);
}
unsafe extern "C" {
    pub fn sapp_keyboard_shown() -> bool;
}
unsafe extern "C" {
    pub fn sapp_is_fullscreen() -> bool;
}
unsafe extern "C" {
    pub fn sapp_toggle_fullscreen();
}
unsafe extern "C" {
    pub fn sapp_show_mouse(show: bool);
}
unsafe extern "C" {
    pub fn sapp_mouse_shown() -> bool;
}
unsafe extern "C" {
    pub fn sapp_lock_mouse(lock: bool);
}
unsafe extern "C" {
    pub fn sapp_mouse_locked() -> bool;
}
unsafe extern "C" {
    pub fn sapp_set_mouse_cursor(cursor: sapp_mouse_cursor);
}
unsafe extern "C" {
    pub fn sapp_get_mouse_cursor() -> sapp_mouse_cursor;
}
unsafe extern "C" {
    pub fn sapp_bind_mouse_cursor_image(
        cursor: sapp_mouse_cursor,
        desc: *const sapp_image_desc,
    ) -> sapp_mouse_cursor;
}
unsafe extern "C" {
    pub fn sapp_unbind_mouse_cursor_image(cursor: sapp_mouse_cursor);
}
unsafe extern "C" {
    pub fn sapp_userdata() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_query_desc() -> sapp_desc;
}
unsafe extern "C" {
    pub fn sapp_request_quit();
}
unsafe extern "C" {
    pub fn sapp_cancel_quit();
}
unsafe extern "C" {
    pub fn sapp_quit();
}
unsafe extern "C" {
    pub fn sapp_consume_event();
}
unsafe extern "C" {
    pub fn sapp_frame_count() -> u64;
}
unsafe extern "C" {
    pub fn sapp_frame_duration() -> f64;
}
unsafe extern "C" {
    pub fn sapp_set_clipboard_string(str_: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn sapp_get_clipboard_string() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn sapp_set_window_title(str_: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn sapp_set_icon(icon_desc: *const sapp_icon_desc);
}
unsafe extern "C" {
    pub fn sapp_get_num_dropped_files() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_get_dropped_file_path(
        index: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn sapp_run(desc: *const sapp_desc);
}
unsafe extern "C" {
    pub fn sapp_egl_get_display() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_egl_get_context() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_html5_ask_leave_site(ask: bool);
}
unsafe extern "C" {
    pub fn sapp_html5_get_dropped_file_size(index: ::std::os::raw::c_int) -> u32;
}
unsafe extern "C" {
    pub fn sapp_html5_fetch_dropped_file(request: *const sapp_html5_fetch_request);
}
unsafe extern "C" {
    pub fn sapp_metal_get_device() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_metal_get_current_drawable() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_metal_get_depth_stencil_texture() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_metal_get_msaa_color_texture() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_macos_get_window() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_ios_get_window() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_d3d11_get_device() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_d3d11_get_device_context() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_d3d11_get_swap_chain() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_d3d11_get_render_view() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_d3d11_get_resolve_view() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_d3d11_get_depth_stencil_view() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_win32_get_hwnd() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_wgpu_get_device() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_wgpu_get_render_view() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_wgpu_get_resolve_view() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_wgpu_get_depth_stencil_view() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_gl_get_framebuffer() -> u32;
}
unsafe extern "C" {
    pub fn sapp_gl_get_major_version() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_gl_get_minor_version() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sapp_gl_is_gles() -> bool;
}
unsafe extern "C" {
    pub fn sapp_x11_get_window() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_x11_get_display() -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn sapp_android_get_native_activity() -> *const ::std::os::raw::c_void;
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __va_list_tag"][::std::mem::size_of::<__va_list_tag>() - 24usize];
    ["Alignment of __va_list_tag"][::std::mem::align_of::<__va_list_tag>() - 8usize];
    ["Offset of field: __va_list_tag::gp_offset"]
        [::std::mem::offset_of!(__va_list_tag, gp_offset) - 0usize];
    ["Offset of field: __va_list_tag::fp_offset"]
        [::std::mem::offset_of!(__va_list_tag, fp_offset) - 4usize];
    ["Offset of field: __va_list_tag::overflow_arg_area"]
        [::std::mem::offset_of!(__va_list_tag, overflow_arg_area) - 8usize];
    ["Offset of field: __va_list_tag::reg_save_area"]
        [::std::mem::offset_of!(__va_list_tag, reg_save_area) - 16usize];
};
